LootJS.modifiers((event) => {
    event
        .addLootTableModifier("cataclysm:entities/the_leviathan")
        .randomChance(1)
        .addLoot("relics:reflection_necklace")
    event
        .addLootTableModifier("cataclysm:entities/ancient_remnant")
        .randomChance(1)
        .addLoot("artifacts:cross_necklace")
    event
        .addLootTableModifier("undead_revamp2:entities/thehunter")
        .randomChance(0.1)
        .addLoot("artifacts:panic_necklace")
    event
        .addLootTableModifier("minecraft:chests/village/village_temple")
        .randomChance(0.05)
        .addLoot("enigmaticlegacy:angel_blessing")
    event
        .addBlockLootModifier("minecraft:coal_block")
        .randomChance(0.002)
        .addLoot("immersive_armors:divine_helmet")
        .addLoot("immersive_armors:divine_chestplate")
        .addLoot("immersive_armors:divine_leggings")
        .addLoot("immersive_armors:divine_boots") 
    event
        .addLootTableModifier("minecraft:chests/abandoned_mineshaft")
        .randomChance(0.15)
        .addLoot("simplyswords:decaying_relic")
    event
        .addLootTableModifier("minecraft:chests/ancient_city")
        .randomChance(0.05)
        .addLoot("simplyswords:decaying_relic")
    event
        .addEntityLootModifier("bosses_of_mass_destruction:lich")
        .addWeightedLoot([
            Item.of("simplyswords:slumbering_lichblade").withChance(33.333),
            Item.of("simplyswords:soulstealer").withChance(33.333),
            Item.of("simplyswords:soulrender").withChance(33.333)
        ])
    event
        .addLootTableModifier("netherexp:brazier_chest/exposed")
        .randomChance(0.2)
        .addLoot("artifacts:obsidian_skull")
    event
        .addLootTableModifier("netherexp:brazier_chest/hidden")
        .randomChance(0.2)
        .addLoot("artifacts:obsidian_skull")
    event
        .addLootTableModifier("bosses_of_mass_destruction:chests/gauntlet")
        .randomChance(0.25)
        .addLoot("simplyswords:emberblade")
    event
        .addLootTableModifier("bosses_of_mass_destruction:entities/void_blossom")
        .randomChance(1)
        .addLoot("relics:spore_sack")
    event
        .addLootTableModifier("cataclysm:entities/ender_guardian")
        .randomChance(1)
        .addLoot("enigmaticlegacy:golem_heart")
    event
        .addLootTableModifier("cataclysm:entities/kobolediator")
        .removeLoot("cataclysm:koboleton_bone")
    event
        .addLootTableModifier("cataclysm:entities/koboleton")
        .removeLoot("cataclysm:koboleton_bone")
    event
        .addLootTableModifier("cataclysm:entities/ancient_remnant")
        .addWeightedLoot(
            [3, 6],
            [Item.of("cataclysm:koboleton_bone").withChance(50)]
        );
    event
        .addLootTableModifier("alexsmobs:entities/void_worm")
        .randomChance(0.25)
        .addLoot("relics:spatial_sign")
    event
        .addLootTableModifier("minecraft:entities/wither")
        .addLoot("enigmaticlegacy:evil_essence")
    event
        .addLootTableModifier("minecraft:entities/wither")
        .addWeightedLoot(
            [1, 3],
            [Item.of("enigmaticlegacy:evil_essence").withChance(25)]
        )
     event
        .addLootTableModifier("minecraft:entities/elder_guardian")
        .randomChance(0.25)
        .addLoot("enigmaticlegacy:guardian_heart")
    event
        .addLootTableModifier("minecraft:entities/ender_dragon")
        .randomChance(0.25)
        .addLoot("enigmaticlegacy:abyssal_heart")
    event
        .addLootTableModifier("cataclysm:entities/scylla")
        .randomChance(0.25)
        .addLoot("enigmaticaddons:thunder_scroll")
});